# Generated by Django 5.0 on 2024-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_event_image_url_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="myapp.worker"
            ),
        ),
    ]
