# Generated by Django 5.0 on 2024-09-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_event_workers"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="clock_in_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_out_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
