# Generated by Django 5.0.4 on 2024-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_attendance_clock_in_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
